---
title: "Community Report Data Viz Demo"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: yeti
params:
  port: "Point Judith, RI"
  port_alt: "POINTJUDITH_RI"
  top: 7

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(flexdashboard)

x <- c("sqldf", "tidyverse", "RcppRoll", "ggthemes", "moments", "gridExtra", "broom", "viridis",
       "ggsci","ggstance", "cowplot", "wesanderson", "kableExtra", "formattable", "UpSetR")

lapply(x, require, character.only = TRUE) ##applying the function require to each point in the vector x

```


```{r, echo =FALSE, warning=FALSE, include=FALSE}
options(scipen = 999)  

#data processing step

gdpdef <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/GDPDEF.csv", header = TRUE))

##geo table 
geo_table <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/geo_table.csv", header = TRUE))

##raw landings file
#byport_thin <- as_tibble(read.csv("//LAZ/Shared/Research/2015_2018_COCA/2_Data/Basic Info/Data/raw_data/byport_thin.csv", header = TRUE))
all_port_landings <- as_tibble(read.csv("C:/Users/brian/Dropbox/COCA/DATA/GMRI_aggregated data/byport_thin.csv", 
                                        header = TRUE)) %>% 
  left_join(., gdpdef, by = c("YEAR" = "year")) %>%
  left_join(., geo_table, by = c("PORT_CODE")) %>% 
  mutate(value_2009 = (value / GDPDEF) * 100) %>% 
  na.omit() %>% 
  rename(spp = SPECIES, year = YEAR) 


#summary ports 
all_port_spp <- all_port_landings %>% 
  group_by(year, port_tidy, spp) %>% 
    summarise(spp_value = sum(value),
      spp_value_2009 = sum(value_2009),
      lbs = sum(lbs))


top_x_port <- function(a, b) ##processing function
{
  filter <- all_port_spp %>% filter(port_tidy == a)
  
  top <- filter %>% 
    group_by(year) %>% 
    top_n(5, spp_value) %>% #top 5 most frequent 
    arrange(year, desc(spp_value))
  
  spp_list <- top %>% group_by(spp) %>% 
    count(spp) %>% ungroup() %>% 
    top_n(b, n) #taking top n (b) most frequent top 5 species
  
  top_list <- filter %>% 
    group_by(spp) %>% 
    mutate(
      spp_10 = case_when(
        !spp %in% spp_list$spp ~ "Other", #if not on the list you can't get it in
        TRUE ~ as.character(spp))) #if on list then spp = spp_10

#defining variables for lapply
    
years <- c(seq(min(top$year), max(top$year), by = 1)) #vector to run through
spp <- unique(top_list$spp_10)
n_spp = length(spp)


  bind <- function(years) {
    cbind(year = rep(years, n_spp), # n of years = n of species
          fake =rep(0, n_spp), # of 0s = n of species 
          spp)
  }
#apply function    
fake_list <- lapply(years, bind)  

#converting list to dataframe
fake_df <- as_tibble(do.call(rbind.data.frame, fake_list)) %>% 
              mutate(
                year = as.numeric(as.character(year)),
                fake = as.numeric(as.character(fake)),
                spp = as.character(spp))


  top_10_sum <- top_list %>% 
    group_by(year, spp_10) %>% 
    summarise(
      value = sum(spp_value),
      value_2009 = sum(spp_value_2009),
      volume = sum(lbs)) %>% 
        right_join(. , fake_df, by = c("year" = "year", "spp_10" = "spp")) %>% 
          mutate_if(is.numeric, funs(ifelse(is.na(.), 0, .))) ##replacing NA w/ zeros
  
  return(data.frame(top_10_sum))
}


top_10_sum <- top_x_port(params$port_alt, params$top)


  #sensible output!!! 
  top_prop <- top_10_sum %>% 
      group_by(year) %>% 
        summarise(total_value = sum(value)) %>% 
          ungroup() %>% 
            left_join(., top_10_sum, by = "year") %>% 
              group_by(spp_10, year) %>% 
                mutate(prop = (value / total_value)) %>% 
                  arrange(year)
  
##issue arising from years in which one of the 'top species' does not appear.  

  totals_df <- top_10_sum %>% group_by(year) %>% 
    summarize(total_value = sum(value),
              total_2009 = sum(value_2009),
              total_volume = sum(volume))
  

```

Port Level Trends
=====================================  

Column 
-------------------------------------

### Top Species Over Time

```{r}
  
  area <- ggplot(top_prop, aes(x=year, y=prop)) +
    geom_area(aes(fill = fct_reorder2(spp_10, year, prop, .desc = FALSE)),  #ordering factor based on proportion
              alpha = .6, size=.4, colour="black") + 
    labs(fill = "Species", scale) +
    scale_y_continuous(name = "% of Total Landings Value", labels = scales::percent) +
    theme_bw() +
    scale_fill_gdocs() +
    labs(title =paste("Proportion of Total Landings Value: Top", params$top, "Species", sep=" "),
         subtitle = paste("Top", params$top, "species = top", params$top, "most frequently top", params$top, sep=" ")) +
  scale_x_continuous(breaks = seq(min(top_prop$year), max(top_prop$year), by = 8))+
      theme(legend.position = "right",
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title.x = element_blank())
  area
```

Column {.tabset}
-------------------------------------

### Landings Value

```{r}
  trend <- ggplot(totals_df, aes(year, total_value/1000000)) + 
    geom_line(color = "black", size = 1.2) + 
    geom_line(data = totals_df, aes(year, total_2009/1000000), color = "red", alpha = .4 ) + 
    theme_bw() +
    labs(title = paste(params$port,": Total Value", sep =""),
         subtitle = "Value plotted in nominal (black) and 2009 dollars (red)") +
        scale_y_continuous(name = "Millions of $") + expand_limits(y=0)+
    scale_x_continuous(breaks = seq(min(top_prop$year), max(top_prop$year), by = 8))+
        theme(axis.title.x = element_blank())

trend
```

### Landings Volume

```{r}
  trend_volume <- ggplot(totals_df, aes(year, total_volume / 1000000)) + 
    geom_line(color = "black", size = 1.2) + 
    theme_bw() +
    labs(title = paste(params$port,": Total Volume", sep =""),
    subtitle = "No adjustment made") +
    scale_y_continuous(name = "Millions of lbs") + expand_limits(y=0) +
    scale_x_continuous(breaks = seq(min(top_prop$year), max(top_prop$year), by = 8))+
    theme(axis.title.x = element_blank())

trend_volume

```

Port Level Trends (Continued)
=====================================  

Fishing Activity 
=====================================  